#!/usr/bin/env bash

## Perform low level bootstrap of new machine, sufficient to allow
#  ansible to take over with  bootstrap_node.yml
#  Specifically, it must
#	 - enable root access via the given key
#   - enable root to login remotely
#  Needs to run on the machine itself !!  chicken and egg, how get the script there?
#   V4_mountedfrom_Icaro/RADclock_mycurrent/Workflow_scripts/VM/bootstrapAccess

if [ `id -u` -ne 0 ]; then
	echo "Sorry `id -un`, this must be run as root"
	exit 0
fi

#AnsibleHome="Users/darryl/Papers/TSCclock/Programs/V4/Ansible/NTC_CommandAndControl"

## Allow root access via Icaro's key
#  Assume already have this for now: is true to all existing snapshots of all VMs, all OSes

## Allow root login  (regardless of current line, commented or not)
echo -e "${RED} Enabling root login${CLE}"
sed -i "" -E 's/^#?PermitRootLogin [n|y]+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

grep Root /etc/ssh/sshd_config  |grep -v setting

## Make it take effect
service sshd reload
