#!/usr/bin/env bash

if [ `id -u` -ne 0 ]; then
        echo "Sorry `id -un`, this must be run as root"
        exit 0
fi

OS=`uname -s`

# OS-agnostic script name, gets renamed when copied to install dir
Name="daemon_startup_script";

case $OS in
	FreeBSD)
		Scriptdir=FreeBSD;
		rcDir="/etc/rc.d";;
	Linux)
		Scriptdir=debian
		distro=`grep ID /etc/*-release  |tail -1 |cut -d'='  -f2`
		if [ $distro != "debian" ]; then
			echo "The startup script is written for debian, your distro is $distro, trying it anyway."
		fi
		rcDir="/etc/init.d";;
	*)
		echo "This script only supports FreeBSD and Debian Linux currently, you are on $OS! sorry.";
		exit;;
esac

echo "Installing $Scriptdir/$Name for $OS as $rcDir/radclock"
cp $Scriptdir/$Name $rcDir/radclock
ls -l  $rcDir/radclock

# Prompt the system initialization `service' system to recognise the new script
case $OS in
	FreeBSD)
		;;
	Linux)
		systemctl daemon-reload
		#service --status-all > \dev\null;;
esac

service radclock status		# test it
