#!/usr/bin/env bash

if [ `id -u` -ne 0 ]; then
        echo "Sorry `id -un`, this must be run as root"
        exit 0
fi

OS=`uname -s`

if [ $OS == FreeBSD ]; then
	$OS/update_FFsource
else
	echo "This script only supports FreeBSD currently, you are on $OS! sorry."
fi
