name: RADclock build system

on:
  push:
    branches: [ RADdev ]
  pull_request:
    branches: [ RADdev ]

jobs:
  tests:
    name: Build kernel packages
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.24
      - uses: actions/checkout@v2
      - name: what version is installed?
        run: earthly --version
      - name: run the earthly hello world
        run: earthly +kernel-build-patched
