name: RADclock build system

on:
  push:
    branches: [ RADdev ]
  pull_request:
    branches: [ RADdev ]

jobs:
  tests:
    name: Build kernel packages
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.24
      - uses: actions/checkout@v2
      - name: Build Debian AMD64 kernel packages
        run: earthly +kernel-build-patched
      - uses: actions/upload-artifact@v2
        with:
          name: Upload packages
          path: artifacts/
